blog/urls.py
from django.conf.urls import url
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('blog/<int:user_id>/', views.mypage, name='mypage'),
    path('blog/index/<int:photo_id>/', views.detail, name='detail'),
    path('<int:photo_id>/good/', views.good, name='good'),
    path('create_pet/', views.create_pet, name='create_pet'),
    path('user_create/', views.UserCreate.as_view(), name='user_create'),
    path('blog/mypage/<int:pet_id>/', views.pet_detail, name='pet_detail'),
    path('blog/<int:pet_id>/edit/', views.pet_edit, name='pet_edit'),

]
"""
URLS.py
    path('products/<int:product_id>/edit/', catalogue.views.product_edit,
         name='product_edit'),

VIEWS.py
def product_edit(request, product_id):
    try:
        product=Product.objects.get(id=product_id)
    except Product.DoesNotExist:
        raise Http404

    if request.method == 'POST':
        form = ProductEditForm(request.POST, instance=product)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('product_detail',
                                               args=(product.id,)))
    else:
        form= ProductEditForm(instance=product)
    return TemplateResponse(request, 'catalogue/product_edit.html',
                   {'form':form,'product':product})

"""

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.
class Pet(models.Model):

    SEX_CHOICES = (
        (0,'オス'),
        (1,'メス'),
        (2,'秘密'),
    )

    PET_CHOICES = (
        (0,'犬'),
        (1,'猫'),
        (2,'その他'),
    )

    name = models.CharField(max_length=40)
    owner = models.ForeignKey(get_user_model(),on_delete=models.CASCADE,null=True)
    sex = models.IntegerField(
        verbose_name = '性別',
        choices = SEX_CHOICES,
        default = 0
    )
    together_with = models.IntegerField(
        verbose_name = 'いつから一緒にいますか？',
        default=1985,
        validators=[MinValueValidator(1985)]
    )
    pet_type = models.IntegerField(
        verbose_name = 'ペットの種類',
        choices = PET_CHOICES,
        default = 0
    )
    created_at = models.DateTimeField(default=timezone.now)


class Photo(models.Model):

    image = models.ImageField(verbose_name='写真',upload_to='images/',)
    good_count = models.IntegerField(default=0)
    pub_date = models.DateTimeField(default=timezone.now)
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE,null=True)
    is_primary = models.BooleanField(verbose_name='表示用として使う',default=False)
    is_dispalyed = models.BooleanField(verbose_name='表示させますか？',default=False)


    def get_filename(self):
        return os.path.basename(self.file.name)


class Good(models.Model):

    created_at = models.DateTimeField(default=timezone.now)
    photo = models.ForeignKey(Photo, on_delete=models.CASCADE)
    good_counter = models.IntegerField(default=0)
    owner = models.ForeignKey(get_user_model(),on_delete=models.CASCADE)

    class Meta:
        db_table = 'good'
        verbose_name = verbose_name_plural = 'いいね'

blog/forms.py
from django import forms
from .models import Photo, Pet
from django.forms import  TextInput, Select, ClearableFileInput
from django.contrib.auth.forms import(
    AuthenticationForm, UserCreationForm
)
from django.contrib.auth import get_user_model
from django.forms import inlineformset_factory

User = get_user_model()


"""
class ModelFormWithFormSetMixin:

    def __init__(self, *args, **kwargs):
        super(ModelFormWithFormSetMixin, self).__init__(*args, **kwargs)
        self.formset = self.formset_class(
            instance=self.instance,
            data=self.data if self.is_bound else None,
        )

    def is_valid(self):
        return super(ModelFormWithFormSetMixin, self).is_valid() and self.formset.is_valid()

    def save(self, commit=True):
        saved_instance = super(ModelFormWithFormSetMixin, self).save(commit)
        self.formset.save(commit)
        return saved_instance
"""

class PhotoSubmitForm(forms.ModelForm):

    class Meta:
        model = Photo
        fields = ['image','is_primary','is_dispalyed']


PetPhotoSet = inlineformset_factory(
    parent_model = Pet,
    model = Photo,
    form = PhotoSubmitForm,
    extra=1,
    can_delete=False,
)


class PetCreateForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Pet
        fields = ['name','sex','pet_type','together_with']

# これがモデルフォームセット
PetCreateFormSet = forms.modelformset_factory(
    Pet, form=PetCreateForm, extra=1
)
PhotoFormset = forms.inlineformset_factory(
    Pet, Photo, fields=['image','is_primary','is_dispalyed'],
    extra=1,can_delete=False
)



"""
class PetForm(ModelFormWithFormSetMixin, forms.ModelForm):

    formset_class = PetPhotoSet

    class Meta:
        model = Pet
        fields = ['name','sex','pet_type','together_with']

"""

class LoginForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label


class UserCreateForm(UserCreationForm):

    class Meta:
        model = User
        if User.USERNAME_FIELD =='email':
            fields = ('email',)
        else:
            fields = ('username', 'email')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class UserUpdateForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username','email']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

blog/views.py
from django.contrib.auth import get_user_model
from django.http import JsonResponse
from django.shortcuts import render, redirect, resolve_url
from django.views.generic.edit import CreateView
from django.core.paginator import Paginator
from django.views import generic
from .models import Photo, Good, Pet
from .forms import PhotoSubmitForm,  PetCreateForm, PhotoFormset
from django.template.response import TemplateResponse
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.db.models import Count
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from .forms import(
    LoginForm, UserCreateForm, UserUpdateForm
)
from django.contrib.auth.views import (
    LoginView, LogoutView
)
from django.contrib import messages

User = get_user_model


def pet_edit(request, pet_id):
    user = request.user
    pet= Pet.objects.get(pk=pet_id)
    if request.method == "POST":
        form = PetCreateForm(request.POST, instance=pet)
        context = {'form':form}
        if form.is_valid():
            pet = form.save(commit=False)
            formset = PhotoFormset(request.POST, files=request.FILES, instance=pet)
            pet.owner = request.user
            pet.save()
            return redirect('index')
    else:
        form = PetCreateForm(instance=pet)
    return render(request, 'blog/pet_edit.html', {'form':form})


def create_pet(request):
    """
    Pet.objects.all.Count() => x
    どこかへreturn させる
    """
    user = request.user
    form = PetCreateForm(request.POST or None)
    context = {'form':form}
    if request.method == 'POST' and form.is_valid():
        pet = form.save(commit=False)
        formset = PhotoFormset(request.POST, files=request.FILES, instance=pet)
        if formset.is_valid():
            pet.owner = user
            pet.save()
            photo = Photo
            formset.save()

            return redirect('/')
        else:
            context['formset'] = formset
    else:
        context['formset'] = PhotoFormset
    return render(request, 'blog/create_pet.html', context)


def index(request):

    if request.method == 'GET':

        best_photos = Photo.objects.order_by('-good_count')[:2]
        photos = Photo.objects.order_by('-good_count')
        paginator = Paginator(photos, 30)
        page = request.GET.get('page', 1)
        photos =  paginator.page(page)

        user = request.user
        goods = Good.objects.all()

        return render(request, 'blog/index.html', {
                'goods':goods,
                'best_photos':best_photos,
                'photos': photos,
                'user': user})


def detail(request, photo_id):

    goods = Good.objects.all()
    photo = Photo.objects.get(pk=photo_id)

    return render(request, 'blog/index/detail.html',{
            'photo': photo,
            'goods':goods})


def pet_detail(request, pet_id):
    pet = Pet.objects.get(pk=pet_id)

    return render(request, 'blog/mypage/pet_detail.html',{
            'pet':pet
    })

def good(request,photo_id):

    photo = Photo.objects.get(pk=photo_id)
    user = request.user
    if photo.pet.owner == user:
        messages.success(request, 'kkkk')
        return redirect('index')

    elif Good.objects.filter(owner=user).filter(photo=photo).count() > 0:
        messages.success(request, 'kkkk')
        return redirect('index')

    else:
        photo.good_count += 1
        photo.save()
        good = Good()
        good.owner = user
        good.photo = photo
        good.save()

        return redirect('index')


def mypage(request, user_id):

    user = request.user
    pet = Pet.objects.filter(owner=user)
    pet_count = Pet.objects.filter(owner=user).count()
    if request.method == 'GET':
        form =  PhotoSubmitForm()
        if Pet.objects.filter(owner=user).count() <10:

            return render(request, 'blog/mypage.html', {
                'pet_count':pet_count,
                'pet':pet,
                'form': form,
                'user': user})

        else:
            return render(request, 'blog/mypage.html', {

                'user': user})

    elif request.method == 'POST':

        form = PhotoSubmitForm(request.POST, request.FILES)
        if not form.is_valid():
            raise ValueError('invalid form')

        photo = form.save(commit=False)

        photo.image = form.cleaned_data['image']
        photo.pet = pet
        photo.save()

        return render(request, '/',{
            'form': form,
            'photo' :photo})


class Login(LoginView):

    form_class = LoginForm
    template_name = 'blog/login.html'


class Logout(LoginRequiredMixin, LogoutView):

    template_name = 'blog/index.html'


class UserCreate(generic.CreateView):

    template_name = 'blog/user_create.html'
    form_class = UserCreateForm

    def form_valid(self, form):

        user = form.save(commit=False)
        user.is_active = False
        user.save()

        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol':'https' if self.request.is_secure() else 'http',
            'domain':domain,
            'token':dumps(user.pk),
            'user':user,
            }
        subject_template = get_template('blog/mail_template/create/subject.txt')
        subject = subject_template.render(context)

        message_template = get_template('blog/mail_template/create/message.txt')
        message = message_template.render(context)

        user.email_user(subject, messsage)

        return redirect('blog:user_create_done')



"""
class UserUpdate(OnlyYouMixin, generic.UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'blog/user_form.html'

    def get_success_url(self):
        return redirect('index')

"""

"""

def good(request, photo_id):
    if request.method == 'POST':
        Good.objects.create(photo_id=photo_id)
    count

        def good(request, photo_id, user_id) すでにあった場合
            return ('2回目です！')
        else
            newする good.create.create(photo_id=photo_id,user_id=user_id)

        good count = count(good(photo_id))
            リレーションの貼り方やり方調べる
        good_countをindexに渡す

        photo_id に対するGoodの数を集計する、結果をindex表示させる

1.　templateで計算させる
2.1 goodで計算する
2.2 indexで計算するphotoに紐づいたgoodを呼び出して数を計算して、表示する。
3.　photoのgood_countを更新する
4.　Photoモデルで計算するメソッド追加して、Goodの数を集計して、indexで表示させる。


1で動かしてみる→２のどちらかで書き直してみる
マイページ

Views
    index
    mypage
    共通の計算したGoodを呼び出して表示する仕組み
        →good_couuntメソッド　を作って、呼び出す。



def upload(request):
    if request.method == 'POST':
        form = PhotoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('/')
        else:
            form = PhotoForm()
        return render(request, 'upload.html', {'form': form})



def good(request, pk):
    photo = Photo.objects.get(pk=pk)
    is_good = Good.objects.count()
    photo.good_count += 1
    photo.save()
    good = Good()
    good.photo = photo
    good.save()
    messages.success(request, 'いいね！しました')
    return redirect('/')
"""

blog/templates/blog/create_pet.html
<!DOCTYPE html>
<html lang="ja">
<head>
  <title>Photo UPLOADING</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
    <body>

      <nav class="navbar navbar">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
              <li class="active"><a href="{% url 'index' %} ">Home</a></li>
              <li class="active"><a href="{% url 'mypage' user.id %} ">マイページへ</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li>ようこそ{{ user.username }}さん</li>
            </ul>
          </div>
        </div>
      </nav>

        <h1>PET</h1>
      <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
                {{ formset.as_table}}
            </table>
            <button type="submit" class="save btn btn-default">保存する</button>
        </form>


    </body>
</html>

blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="ja">
<head>
  <title>Photo UPLOADING</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<style>

footer {

  padding: 25px;
}
  .carousel-inner img {
    width: 300px; /* Set width to 100% */
    margin: auto;
    min-height:30px;
  @media (max-width: 400px) {
  .carousel-caption {
   display: none;
    }
  }
}
</style>
</head>
<body>

<nav class="navbar ">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
       <ul class="navbar-nav mr-auto">
         {% if user.is_authenticated %}
         <li>
           <a class="nav-item nav-link" href="{% url 'logout' %}">ログアウト</a>
           <a href="{% url 'mypage' user.id %} ">マイページへ</a></li>


         </li>
         {% else %}
         <li class="nav-item">
           <a class="nav-item nav-link" href="{% url 'login' %}">
           ようこそ、ゲスト！ログインはこちら
         </a>
         </li>
         {% endif %}
       </ul>
     </div>

     <div id="myCarousel" class="carousel slide" data-ride="carousel">
         <!-- Indicators -->
         <ol class="carousel-indicators">
           <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
           <li data-target="#myCarousel" data-slide-to="1"></li>
         </ol>

         <!-- Wrapper for slides -->
         <div class="carousel-inner" role="listbox">
           <div class="item active">
             <img class="img-fluid" src="/media/{{ best_photos.0.image }}" >
             <div class="carousel-caption">
               <h3>今週の１位</h3>
               <p>Money Money.</p>
             </div>
           </div>

           <div class="item">
             <img class="img-fluid" src="/media/{{ best_photos.1.image }}" >
             <div class="carousel-caption">
               <h3>今週の２位</h3>
               <p>Lorem ipsum...</p>
             </div>
           </div>
         </div>

         <!-- Left and right controls -->
         <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
           <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
           <span class="sr-only">Previous</span>
         </a>
         <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
           <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
           <span class="sr-only">Next</span>
         </a>
     </div>
<hr>

{% for pho in photos %}
{% if pho.is_dispalyed == True %}
  <div class="col-sm-4">
    <div class="panel panel-primary">
      <div class="panel-heading"> <p>{{ pho.pet.owner.username }}さんの {{ pho.pet.name }}ちゃん {{ pho.pet.get_sex_display }}</p></div>
      <div class="panel-body"><img class="img-responsive" src="/media/{{ pho.image }}" class="img-responsive" width="250" height="20" alt="Image"></div>
      <div class="panel-footer">

        <li><a href="{% url 'detail' photo_id=pho.id %} ">詳細はこちらから</a></li>

        <form action="{% url 'good' pho.id %}" method="post">
        {% csrf_token %}

        <input type="submit" name="good" value="いいね！">

        </form>

        <p> ({{ pho.good_count }}) いいね！</p>

      </div>
    </div>
  </div>

        {% else %}
        <div class="col-sm-4">
        <div class="panel panel-primary">
        <div class="panel-heading">{{ pho.get_category_display }} ID:{{ pho.id }}</div>
        <div class="panel-body">
          <img class="img-responsive" src="/media/images/cat_free.jpg" width="250" height="20" alt="Image">
        </div>

        <div class="panel-footer">
        <p>{{ pho.owner.username }}さんの{{ pho.name }}ちゃん</p>
        <li><a href="{% url 'detail' photo_id=pho.id %} ">詳細はこちらから</a></li>

        <form action="{% url 'good' pho.id %}" method="post">
          {% csrf_token %}

        <input type="submit" name="good" value="いいね！">
      </form>
        <p>{{ pho.owner.username }} {{ pho.good_count }} いいね！</p>
      </div>
    </div>
  </div>
  {% endif %}
  {% endfor %}


<hr>
<footer class="container-fluid text-center">
  ///
    {% if photos.has_previous %}
  <a href="?page={{ photos.previous_page_number }}">&lt; 前のページ</a>
  {% else %}
  <span>&lt; 前のページ</span>
  {% endif %}

  {% if photos.has_next %}
  <a href="?page={{ photos.next_page_number }}">次のページ &gt;</a>
  {% else %}
  <span>次のページ;&lt; </span>
  {% endif %}

  <p>Footer Text</p>


</footer>
</body>
</html>

blog/templates/blog/login.html
<div class="row">
  <div class="col-sm-3 sidenav">
  </div>
    <div class="col-sm-6">
    <div class="card-body">
      <form action="{% url 'login' %}"method=="POST">

               {{ form.non_field_errors }}
               {% for field in form %}
                  {{ field }}
                  {{ field.errors }}
                   <br>
               {% endfor %}
               <button type="submit" class="btn btn-success btn-lg btn-block" >ログイン</button>
               <input type="hidden" name="next" value="{{ next }}" />
               {% csrf_token %}
        </form>
      </div>
    <div class="card-body">
      <a href="{% url 'user_create' %}" class="btn btn-success btn-lg btn-block">初めての方はこちらから</a>
    </div>
    <div class="col-sm-2 sidenav">
    </div>
  </div>
</div>

blog/templates/blog/mypage.html
<!DOCTYPE html>
<html lang="ja">
<head>
  <title>Photo UPLOADING</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<style>

  footer {
    background-color: #f2f2f2;
    padding: 25px;
  }

</style>
</head>
<body>

<nav class="navbar navbar">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'index' %} ">Home</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>ようこそ{{ user.username }}さん</li>
      </ul>
    </div>
  </div>
</nav>


{% for pet in user.pet_set.all %}
{% for photo in pet.photo_set.all %}
  {% if photo.is_primary == True %}
<div class="col-sm-4">
  <div class="panel panel-primary">
    <div class="panel-heading"> PET ID{{ photo.pet_id }} {{ photo.pet.name}}</div>
    <div class="panel-body"><img src="/media/{{ photo.image }}" class="img-responsive" width="250" height="20" alt="Image"></div>
    <div class="panel-footer">

      <li><a href="{% url 'pet_detail' pet.id %}">詳細はこちらから</a></li>
      <a class="btn btn-default" href="{% url 'pet_edit' pet.id %}"><span class="glyphicon glyphicon-pencil"></span></a>
          <p>({{ photo.good_count }})いいね！</p>

    </div>
  </div>
</div>
  {% endif %}
{% endfor %}
{% endfor %}

<hr>
<footer class="container-fluid text-center">

  <h3><ul class="active"><a href="{% url 'create_pet' %}">ペットの新規登録はこちらから</a></ul></h3>

  <p>Footer Text</p>
</footer>


</body>
</html>

blog/templates/blog/pet_edit.html
<html>
    <head>
        <title>PETEDIT</title>
    </head>
    <body>


<form action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <table>
          {{ form.as_table }}
          {{ formset.as_table}}
      </table>
      <button type="submit" class="save btn btn-default">Save</button>
  </form>


</body>
</html>

blog/templates/blog/user_create.html
<form action="" mthod="POST">
  {{ form.non_field_errors }}
  {% for field in form %}
  <div class="form-group">
    <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
    {{ field }}
    {{ field.errors }}
  </div>
  {% endfor %}
  {% csrf_token %}
  <button type="submit" class="btn btn-primary btn-lg">送信</button>
</form>

blog/templates/blog/user_form.html
<form action="" method="POST">
    {{ form.non_field_errors }}
    <table class="table">
        <tbody>
            {% for field in form %}
                <tr>
                    <th><label for="{{ field.id_for_label }}">{{ field.label }}</label></th>
                    <td>{{ field }} {{ field.errors }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% csrf_token %}
    <button type="submit" class="btn btn-success btn-lg" >送信</button>
</form>